<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>ChecksumDrop_64.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ChecksumDrop.png" />
    <None Remove="ChecksumDrop.svg" />
    <None Remove="Resources\fabric-icons-6c64f64d.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ChecksumDrop_64.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SHA3.Net" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ChecksumDrop.png" />
    <Resource Include="ChecksumDrop.svg" />
    <Resource Include="Resources\fabric-icons-6c64f64d.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\User.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>User.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\User.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>User.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\ChecksumDrop.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>